# Generated by Django 5.0.1 on 2024-01-17 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quanlity',
            new_name='quantity',
        ),
    ]
